### ISSUE TITLE
Default chromecast isn't initialised

### ISSUE THREAD

**Issue by Elleo** [alexdelorenzo/chromecast_mpris#3]
If a chromecast isn't specified with the "-n" option the first detected chromecast is selected as the default, however it isn't initialised correctly so the status property returns None

**Comment by alexdelorenzo** [comment]
Thanks for taking the time to submit a bug report. This issue was fixed and should not occur in `chromecast_mpris>=0.2.3` on PyPI.

I'm going to close this issue, but feel free to reopen it or comment back if the issue persists.
